version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: myapp

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - app
    env_file:
      - .env
    extra_hosts:  # linux에서는 host.docker.internal을 별도 IP랑 맵핑을 해줘야함
      - "host.docker.internal:${INTERNAL_PRIVATE_IP}"
    restart: unless-stopped

